substitutions:
  _REGION: "europe-west1"
  _AR_REPO: "hello-repo"
  _ENV: "dev"
  _SERVICE_NAME: "hello-world"

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'

steps:
  # 1. Run tests.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Test'
    args:
      - 'build'
      - '--target=build'
      - '-t'
      - 'test-image'
      - '.'

  # 2. Build the final production container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    waitFor: ['Test']
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}-${_ENV}:${SHORT_SHA}',
      '.'
    ]

  # 3. Push the container image to Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}-${_ENV}:${SHORT_SHA}'
    ]

  # 4. Deploy the "Green" (new) version.
  # Use 'gcloud run deploy' to create or update the service.
  # The '--no-traffic' flag is key: it creates a new revision but sends 0% of traffic to it.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Green'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '${_SERVICE_NAME}-${_ENV}',
      '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}-${_ENV}:${SHORT_SHA}',
      '--region=${_REGION}',
      '--platform=managed',
      '--allow-unauthenticated',
      '--no-traffic'
    ]

  # 5. Shift Traffic to make "Green" the new "Blue".
  # This step switches 100% of traffic to the latest deployed revision.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Shift Traffic'
    entrypoint: gcloud
    args: [
      'run', 'services', 'update-traffic', '${_SERVICE_NAME}-${_ENV}',
      '--region=${_REGION}',
      '--to-latest'
    ]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}-${_ENV}:${SHORT_SHA}'
